### ISSUE TITLE
Alternative apps with same functionality?

### ISSUE THREAD

**Issue by pixel2user** [amnesica/Feedsta#4]
If this app is not maintained any longer. Which is the best alternative?

Barinsta (Simple yet advanced Instagram client) - https://f-droid.org/app/me.austinhuang.instagrabber
"For those not having an account, you can access public profiles/hashtags/locations (depends on availability)"

**Comment by amnesica** [comment]
@pixel2user AFAIK Barinsta has the same rate limiting issue Feedsta has
